version: '3.9'

services:
  backend:
    build: ./backend
    container_name: emergent_backend
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "8001:8001"
    depends_on:
      - mongodb
    networks:
      - emergent_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/api/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongodb:
    image: mongo:6.0
    container_name: emergent_mongodb
    restart: always
    environment:
      MONGO_INITDB_DATABASE: emergent_db
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - emergent_net
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  emergent_net:

volumes:
  mongo_data:
